coverage:
  status:
    project:
      default:
        target: auto
        threshold: 70%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        branches:
          - develop
        if_ci_failed: error
        informational: false
        only_pulls: false