server:
  port: 9000
  address: localhost

spring:
  application:
    name: ticket-service
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017
logging:
  level:
    root: info
